version: '3' 
services: 
  zookeeper: 
    image: wurstmeister/zookeeper 
    container_name: zookeeper 
    ports: 
      - "2181:2181" 
    networks:
      - kafka-net
  kafka: 
    image: wurstmeister/kafka 
    container_name: kafka 
    ports: 
      - "9092:9092" 
    networks:
      - kafka-net
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT 
      
  kafka-ui: 
    image: provectuslabs/kafka-ui 
    container_name: kafka-ui 
    ports: 
      - "8090:8080" 
    networks:
      - kafka-net
    depends_on: 
      - kafka 
      - zookeeper 
    environment: 
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
networks:
  kafka-net:
    driver: bridge
